PreCommit:
  EsLint:
    enabled: true
    exclude:
      - 'coverage/**/*js'
      - 'lib/**/*js'
      - 'node_modules/**/*js'

PostCheckout:
 ALL:
   quiet: true
 IndexTags:
   enabled: true
 NpmInstall:
   enabled: true
PostCommit:
 ALL:
   quiet: true
 IndexTags:
   enabled: true
 NpmInstall:
   enabled: true
PostMerge:
 ALL:
   quiet: true
 IndexTags:
   enabled: true
 NpmInstall:
   enabled: true
PostRewrite:
 ALL:
   quiet: true
 IndexTags:
   enabled: true
 NpmInstall:
   enabled: true
